/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData hair_clip = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hair_curler_curler_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cream_svgrepo_com = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barber_shop_svgrepo_com = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barbershop_barber_svgrepo_com = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hair_brush_hairbrush_svgrepo_com = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beard_svgrepo_com__1_ = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hairbrush_hair_salon_svgrepo_com = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirror_makeup_svgrepo_com = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cream_skin_svgrepo_com__1_ = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hot_stones_svgrepo_com = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cream_skin_svgrepo_com__2_ = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bow_tie_svgrepo_com = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hair_salon_svgrepo_com = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hair_brush_hairbrush_svgrepo_com__1_ = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_watch_svgrepo_com = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moustache_svgrepo_com = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData razor_barber_svgrepo_com = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beard_svgrepo_com = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cream_skin_svgrepo_com = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
